var nome = "Luís Fernando Peretti";
var idade = 27;
var idade2 = 10;
var frase = "XV de JAÚ é o melhor time do mundo!!!";
//alert(nome + " tem " + idade + " anos.");
//alert(idade + idade2);
console.log(nome);
console.log(idade + idade2);
console.log(frase);
console.log(frase.replace("XV de JAÚ", "São Paulo FC"));
//alert(frase.replace("XV de JAÚ", "São Paulo FC"));
console.log(frase.toUpperCase());
console.log(frase.replace("XV de JAÚ", "São Paulo FC").toLowerCase());